### ISSUE TITLE
关于rn实现数字滚动动画

### ISSUE THREAD

**Issue by crazyandcoder** [jessieeeee/SimpleOne#10]
hi，作者你好，我在你的博客上面看到一篇文章[实现rn 的数字滚动效果](https://jessiekate.gitee.io/2018/07/09/RN-NumberScroll/)，我看了一下你的代码，代码里面实现的是单向滚动，即：0到6的话，滚动数字是0，1，2，3，4，5，6。如果是6到3的话，滚动数字是6，5，4，3。这种是单向滚动的。假如我想实现循环滚动该如何做？即如果6到3的话，我想滚动方向是6，7，8，9，0，1，2，3这种模式，即循环滚动，你里面的代码是：

`const getPosition = ({ text, items, height }) => {
    // 获得文本在数组的下标
    const index = items.findIndex(p => p === text);

    // 返回文本绘制的y轴坐标
    return index * height * -1;
};`

请问该如何实现？

**Comment by jessieeeee** [comment]
说下我的思路，首先index就不能用findIndex了，因为这里回到0会反向滚动，所以index只能继续递增，继续向上滚动，本身渲染的view数组是从0-9的Text
`
this.props.rotateItems.map(v => (
            <Text key={v} style={[this.props.textStyle, this.props.height]}>
                {v}
            </Text>
        ))
`
当数字渲染到9时，向这个view数组中继续添加后面需要渲染的Text，且数字从0开始递增，下一次循环也是这样，就是你要的效果了

**Comment by crazyandcoder** [comment]
谢谢，我也是该思路
